server:
  port: 8084

spring:
  application:
    name: chat-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/chat-service?authSource=admin
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

app:
  services:
    profile: "http://localhost:8080"

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600  # in seconds
  refreshable-duration: 720000  # in seconds
