server:
  port: 8084  # Cổng

spring:
  application:
    name: chat-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/chat-service?authSource=admin
  datasource:
    url: jdbc:mysql://localhost:3306/chat
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root

    servlet:
      multipart:
        max-file-size: 10MB  # Giới hạn kích thước file tối đa là 10MB
        max-request-size: 100MB  # Giới hạn kích thước request tối đa là 100MB
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600  # in seconds
  refreshable-duration: 720000  # in seconds
