# These are supported funding model platforms

github: [qnguyeen, hatuan1423] # Các nhà tài trợ qua GitHub Sponsors: 
thanks_dev: [Trần Quốc Nguyên, Dương Hà Tuấn]
custom: ['https://github.com/qnguyeen', 'https://github.com/hatuan1423'] # URL tùy chỉnh cho nhà tài trợ
