server:
  port: 8083  # Cổng cho post-service
  servlet:
    context-path: /post  # Cấu hình context path cho post-service

spring:
  application:
    name: post-service  # Tên ứng dụng cho post-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/post-service?authSource=admin  # Kết nối MongoDB cho post-service

  datasource:
    url: "jdbc:mysql://localhost:3306/Data_Firstt"  # Cấu hình kết nối MySQL
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update  # Cập nhật schema JPA tự động
    show-sql: true  # Hiển thị SQL khi thực hiện các query

  servlet:
    multipart:
      max-file-size: 10MB  # Giới hạn kích thước file tối đa là 10MB
      max-request-size: 100MB  # Giới hạn kích thước request tối đa là 100MB
cloud:
  aws:
    credentials:
      access-key: AKIATCKANL35JUXP2NFF
      secret-key: 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
    region:
      static: ap-southeast-2
    stack:
      auto: false


application:
  bucket:
    name: image-0