server:
  port: 8083

spring:
  config:
    activate:
      on-profile: test
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/post-service?authSource=admin
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  elasticsearch:
    uris: https://localhost:9200


cloud:
  aws:
    credentials:
      access-key: AKIATCKANL35JUXP2NFF
      secret-key: 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
    region:
      static: ap-southeast-2
    stack:
      auto: false

application:
  bucket:
    name: image-0
feign:
  client:
    config:
      profile-service:
        load-balancer:
          enabled: true

profile-service:
  url: http://localhost:8081

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: post-service
    server: http://localhost:${server.port}
    title: Post service
    version: 1.0.0