server:
  port: 8083

spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/post-service?authSource=admin
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
