server:
  port: 8083

spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/post-service?authSource=admin
  datasource:
    url: jdbc:mysql://localhost:3306/post
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update  # Cập nhật schema JPA tự động
    show-sql: true  # Hiển thị SQL khi thực hiện các query
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

cloud:
  aws:
    credentials:
      access-key: AKIATCKANL35JUXP2NFF
      secret-key: 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
    region:
      static: ap-southeast-2
    stack:
      auto: false

application:
  bucket:
    name: image-0

feign:
  client:
    config:
      profile-service:
        load-balancer:
          enabled: true

profile-service:
  url: http://localhost:8081

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: post-service
    server: http://localhost:${server.port}
    title: Post service
    version: 1.0.0