server:
  port: 8083

spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/post-service?authSource=admin

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
