server:
  port: 8082
#  servlet:
#    context-path: /notification

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/Data_Firstt"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  application:
    name: notification-service
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 12345678
  profiles:
    active: @spring.profiles.active@