
app:
  api-prefix: /api/v1
spring:
  config:
    activate:
      on-profile: prod
  devtools:
    add-properties: false
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/identity/**, ${app.api-prefix}/api-docs/identity-service
          filters:
            - StripPrefix=2
        - id: profile-service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/profile/users/**, ${app.api-prefix}/api-docs/profile-service
          filters:
            - StripPrefix=2
        - id: notification-service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/notification/**, ${app.api-prefix}/api-docs/notification-service
          filters:
            - StripPrefix=2
        - id: post-service
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/post/**, ${app.api-prefix}/api-docs/post-service
          filters:
            - StripPrefix=2

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

