
spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://localhost:8080
          predicates:
            - Path=/identity/**, /v3/api-docs/identity-service/**
          filters:
            - RewritePath=/identity/(?<segment>.*), /$\{segment} # thay thế ký tự /identity/ thành /
            # http://localhost:8888/identity/users/registration
            # http://localhost:8080/users/registration

        - id: profile-service
          uri: http://localhost:8081
          predicates:
            - Path=/profile/**, /v3/api-docs/profile-service
          filters:
            - RewritePath=/profile/(?<segment>.*), /$\{segment}


        - id: notification-service
          uri: http://localhost:8082
          predicates:
            - Path=/notification/**, /v3/api-docs/notification-service
          filters:
            - RewritePath=/notification/(?<segment>.*), /$\{segment}


        - id: post-service
          uri: http://localhost:8083
          predicates:
            - Path=/post/**, /v3/api-docs/post-service
          filters:
            - RewritePath=/post/(?<segment>.*), /$\{segment}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway
      - url: /v3/api-docs/identity-service
        name: Identity Service
      - url: /v3/api-docs/profile-service
        name: Profile Service
      - url: /v3/api-docs/notification-service
        name: Notification Service
      - url: /v3/api-docs/post-service
        name: Post Service
