server:
  port: 8888

spring:
  application:
    name: api-gateway
  profiles:
    active: @spring.profiles.active@

#https://docs.spring.io/spring-cloud-gateway/reference/spring-cloud-gateway/request-predicates-factories.html
