server:
  port: 8080
  servlet:
    context-path: /identity  # Cấu hình context path cho identity service

spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/post-service?authSource=admin # Kết nối MongoDB
  datasource:
    url: "jdbc:mysql://localhost:3306/Data_Firstt"   # Cấu hình kết nối MySQL
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update  # Cập nhật tự động schema JPA
    show-sql: true      # Hiển thị các câu lệnh SQL
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB  # Cấu hình upload file lớn trong Spring Boot
  kafka:
    bootstrap-servers: localhost:9094  # Kafka broker
    consumer:
      group-id: identity-service
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer  # Key vẫn dùng StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer  # Sử dụng JsonSerializer để serialize GroupEvent
      properties:
        spring.json.value.default.type: com.LinkVerse.identity.entity.GroupEvent  # Đảm bảo Kafka biết loại của đối tượng
        spring.json.trusted.packages: "*"  # Cho phép deserializer đọc các package ngoài Spring

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij" # JWT ký khóa
  valid-duration: 3600 # Thời gian sống của JWT (1 giờ)
  refreshable-duration: 720000 # Thời gian refreshable của JWT (200 giờ)

app:
  services:
    profile: "http://localhost:8081/profile"  # URL của profile service
