server:
  port: 8083

spring:
  config:
    activate:
      on-profile: test
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/post-service?authSource=admin

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: post-service
    server: http://localhost:${server.port}
    title: Post service
    version: 1.0.0