server:
  port: 8085
  servlet:
    context-path: /friend  # Cấu hình context path cho identity service

spring:
  application:
    name: Friend-Service
  data:
    mongodb:
      uri: ${URL_MGDB}
  datasource:
    url: ${URL_SQL}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${USERNAME_SQL}
    password: ${PASS_SQL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  signerKey: ${KEY_JWT}
  valid-duration: 3600
  refreshable-duration: 720000

app:
  services:
    profile: "http://localhost:8081/profile"
